### ISSUE TITLE
Reduce local build and test time

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#303] opened 2017-06-13 14:48 UTC
Now that we have separate csproj's per problem our test and build time has grown quite a bit:
```
========================================
Default
========================================

Task                           Duration
---------------------------------------------------
Clean                          00:00:00.1835870
CopyExercises                  00:00:01.1743155
RestoreNugetPackages           00:00:40.1306513
BuildStubImplementations       00:01:09.1509081
EnableAllTests                 00:00:00.0993630
TestRefactoringProjects        00:00:14.7734888
ReplaceStubWithExample         00:00:00.1808265
TestUsingExampleImplementation 00:10:54.2394493
Default                        00:00:00.7327512
---------------------------------------------------
Total:                         00:13:00.6653407
```

The `TestUsingExampleImplementation` is taking the bulk of the time although all of the sub-tasks that it is doing are parallelizable. Running them in parallel could significantly reduce the build time.

**Comment by robkeim** [comment] 2017-06-13 14:53
Maybe I'm missing something here as in https://github.com/exercism/xcsharp/issues/216 it states the builds are now run in parallel. Is there something I need to configure to enable the parallelization?

**Comment by ErikSchierboom** [comment] 2017-06-13 16:47
Well, they don't actually run in parallel I think. We could do that rather easily I think by modifying the build script. The problem is that you cannot run the dotnet test command on a solution file. That is possible for restoring and building, but not for testing unfortunately.

**Comment by jpreese** [comment] 2017-08-23 12:55
Closing!

**Closed by jpreese** 2017-08-23 12:55 UTC

**Comment by robkeim** [comment] 2017-08-23 16:37
Thanks for your work on this @jpreese! 🎉

I was looking at the build and after your changes and this is the current state:
```
Task                           Duration
---------------------------------------------------
Clean                          00:00:01.0026434
CopyExercises                  00:00:06.8279400
RestoreNugetPackages           00:00:26.6270243
EnableAllTests                 00:00:00.1144599
TestRefactoringProjects        00:00:08.2498699
ReplaceStubWithExample         00:00:00.1723076
TestUsingExampleImplementation 00:03:01.3678156
Default                        00:00:00.0064392
---------------------------------------------------
Total:                         00:03:44.3684999
```

The time is getting eaten up by `RestoreNugetPackages` (~30s) and `TestUsingExampleImplementation` (~3m).

I looked into each of their settings briefly but couldn't find any settings to significantly speed up either of their execution times unfortunately :(

```
var dotNetCoreRestoreSettings = new DotNetCoreRestoreSettings
{
    DisableParallel = false,
    DiagnosticOutput = false,
    NoCache = false
};
```

I was hoping at least the caching would give us a boost locally (which is the performance I'm more concerned about because that has a bigger impact on the development cycle), but it didn't budge. One thing is the cake documentation doesn't seem to specify the default value for any of their configuration params, or at least I couldn't find it anywhere.

For running the tests I saw a lot of output being written to the console and I was wondering if there was cross thread contention for writing to the console, so I tried this:
```
var dotNetCoreTestSettings = new DotNetCoreTestSettings
{
    Verbosity = DotNetCoreVerbosity.Quiet,
    DiagnosticOutput = false
};
```

These settings got a speedup of ~10s, but I didn't verify over multiple runs or what the experience is like when tests fail (ex: is there enough information to debug in a failed test when it's outputting on quiet mode).

I just wanted to  write down those ramblings to have a trace of it in case someone comes back to this someday. Being under 4 minutes is an incredible improvement though cutting down the time by 2/3 locally!

**Comment by ErikSchierboom** [comment] 2017-08-23 17:15
@robkeim We might also be able to cut down of the .NET restore time by caching the NuGet packages: https://docs.travis-ci.com/user/caching/

**Comment by jpreese** [comment] 2017-08-23 17:30
@robkeim yeah some of the documentation seemed lacking, so I mostly dug through their github repo. For example the default restore settings can be found here: https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs

It's just a boolean, so it'll default to false anyway which is probably why you didn't see movement.
